### ISSUE TITLE
close

### ISSUE THREAD

**Issue by zhangyd-c** [wossoneri/CircularProgressBar#3]
https://www.cnblogs.com/rossoneri/p/4446440.html
你文章里留的[新博客地址]()你确定不是故意的么？ 
sq网站啊大哥！

**Comment by wossoneri** [comment]
谢谢提醒...网站到期被别人买走了...还有留言就别贴url了，留多了反而给这个网址增加seo

**Comment by zhangyd-c** [comment]
请把这个issue删掉吧，原文里的评论我也删掉了。

**Comment by wossoneri** [comment]
> 请把这个issue删掉吧，原文里的评论我也删掉了。

Github删不掉issue吧  编辑锁定了
